easy_admin:
    entities:
        Outing:
            class: App\Entity\Outing
            label: 'Sorties'
            list:
                fields:
                    - { property: title, label: Titre }
                    - { property: startDate, label: Date }
                    - { property: author, label: Organisateur }
#                    - { property: active, label: Actif, type: toggle }
            form:
                fields:
                    - { property: author, label: Organisateur }
                    - { property: title, label: Titre }
                    -
                        property: startDate
                        label: 'Date/Heure'
                        type_options:
                            years: [2020,2021,2022,2023]
                            time_label: 'Heure de d√©but :'
                    - { property: body, label: Descriptif, type: 'fos_ckeditor' }
            edit:
                fields:
                    - { property: author, label: Organisateur, type_options: { disabled: true } }
